# Naive Forecasts

In [1]:
import pandas as pd
import sys 

from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.models.naive import *

In [2]:
inf_data = pd.read_csv('..//data//processed//combined_macro_data.csv', index_col = 'Date')
inf_data.index = pd.to_datetime(inf_data.index)
inf_data = inf_data.asfreq('MS')
inf_data.head()

            InflationRate  USD_PHP  UnemploymentRate  DubaiCrude
Date
1958-01-01        6.25000      2.0               NaN         NaN
1958-02-01        6.25000      2.0               NaN         NaN
1958-03-01        5.46875      2.0               NaN         NaN
1958-04-01        5.46875      2.0               NaN         NaN
1958-05-01        6.25000      2.0               NaN         NaN

In [3]:
n_splits = 5
months_forecast = 6
test_size = months_forecast
target_col = 'InflationRate'
inf_train = inf_data[:-test_size]
inf_test = inf_data[-test_size:]

## Train evaluation

In [4]:
naive_test(inf_train, n_splits = n_splits, test_size = test_size, target_col = target_col)

Folds: 5
Test Size: 6

          RMSE       MAE       MSE       MAPE       STD
Fold
1     1.227821  1.061394  1.507544  22.708721  0.617241
2     0.661778  0.530561  0.437950  16.417561  0.395544
3     1.219185  1.026250  1.486412  43.280256  0.859741
4     0.785513  0.709681  0.617031  43.580141  0.644405
5     0.311222  0.284694  0.096859  20.045317  0.256492

In [5]:
seasonal_naive_test(inf_train, n_splits = n_splits, test_size = test_size, target_col = target_col)

Folds: 5
Test Size: 6

          RMSE       MAE        MSE        MAPE       STD
Fold
1     2.149461  1.807935   4.620182   38.661880  0.617241
2     4.225573  4.034410  17.855468  117.761842  0.395544
3     2.368591  2.061278   5.610224   84.475639  0.859741
4     1.783854  1.562246   3.182136   97.369647  0.644405
5     1.920483  1.572914   3.688255  128.888341  0.256492

## II. Test results

In [6]:
n_test_forecast = naive_forecast(inf_train, target_col = target_col, months_ahead = months_forecast)
eval_metrics(inf_test['InflationRate'], n_test_forecast)

{'RMSE': 3.3766148757689987,
 'MAE': 2.55441858874094,
 'MSE': 11.401528019264491,
 'MAPE': 50.272483776475475,
 'STD': 2.2082739170581256}

In [7]:
sn_test_forecast = seasonal_naive_forecast(inf_train, target_col = target_col, months_ahead = months_forecast)
eval_metrics(inf_test['InflationRate'], sn_test_forecast)

{'RMSE': 3.4424841899652194,
 'MAE': 2.6508167622308973,
 'MSE': 11.850697398160493,
 'MAPE': 56.028851147328716,
 'STD': 2.2082739170581256}

## III. Naive forecast

In [8]:
naive = naive_forecast(inf_data, target_col, months_forecast)
naive.to_csv('..//outputs//forecasts//naive_forecast.csv')

In [9]:
seasonal_naive = seasonal_naive_forecast(inf_data, target_col, months_forecast)
seasonal_naive.to_csv('..//outputs//forecasts//seasonal_naive_forecast.csv')