# Naive Forecasts

In [1]:
import pandas as pd
import sys 

from pathlib import Path

project_root = Path.cwd().parent
sys.path.append(str(project_root))

from src.models.naive import *

In [2]:
inf_data = pd.read_csv('..//data//processed//combined_macro_data.csv', index_col = 'Date')
inf_data.index = pd.to_datetime(inf_data.index)
inf_data = inf_data.asfreq('MS')
inf_data.head()

            InflationRate  USD_PHP  UnemploymentRate  DubaiCrude  TargetRRP
Date
1958-01-01        6.25000      2.0               NaN         NaN        NaN
1958-02-01        6.25000      2.0               NaN         NaN        NaN
1958-03-01        5.46875      2.0               NaN         NaN        NaN
1958-04-01        5.46875      2.0               NaN         NaN        NaN
1958-05-01        6.25000      2.0               NaN         NaN        NaN

In [3]:
n_splits = 5
months_forecast = 12
test_size = months_forecast
target_col = 'InflationRate'
inf_train = inf_data[:-test_size]
inf_test = inf_data[-test_size:]

## Train evaluation

In [4]:
naive_test(inf_train, n_splits = n_splits, test_size = test_size, target_col = target_col)

Folds: 5
Test Size: 12

          RMSE       MAE        R2       STD  RMSE/STD
Fold
1     1.311391  1.055347 -1.805766  0.782900  1.675042
2     0.988967  0.740575 -0.179733  0.910521  1.086155
3     1.492747  1.220889 -1.209910  1.004151  1.486576
4     1.479384  1.314080 -1.926316  0.864809  1.710648
5     1.632575  1.484359 -2.438819  0.880376  1.854405

In [5]:
seasonal_naive_test(inf_train, n_splits = n_splits, test_size = test_size, target_col = target_col)

Folds: 5
Test Size: 12

          RMSE       MAE         R2       STD  RMSE/STD
Fold
1     1.663316  1.524544  -3.513743  0.782900  2.124557
2     1.378721  1.189344  -1.292837  0.910521  1.514212
3     3.596012  3.193425 -11.824617  1.004151  3.581147
4     3.381186  3.002995 -14.286123  0.864809  3.909747
5     2.150826  1.868627  -4.968621  0.880376  2.443076

## II. Test results

In [6]:
n_test_forecast = naive_forecast(inf_train, target_col = target_col, months_ahead = months_forecast)
eval_metrics(inf_test['InflationRate'], n_test_forecast)

{'RMSE': 2.864234259264297,
 'MAE': 1.881748300280811,
 'R2': -0.6700698190595198,
 'STD': 2.2163646830352124,
 'RMSE/STD': 1.2923118118548325}

In [7]:
sn_test_forecast = seasonal_naive_forecast(inf_train, target_col = target_col, months_ahead = months_forecast)
eval_metrics(inf_test['InflationRate'], sn_test_forecast)

{'RMSE': 3.065220229143442,
 'MAE': 2.3324472782169186,
 'R2': -0.9126738650436403,
 'STD': 2.2163646830352124,
 'RMSE/STD': 1.382994528204519}

## III. Naive forecast

In [8]:
naive = naive_forecast(inf_data, target_col, months_forecast)
naive.to_csv('..//outputs//forecasts//naive_forecast.csv')

In [9]:
seasonal_naive = seasonal_naive_forecast(inf_data, target_col, months_forecast)
seasonal_naive.to_csv('..//outputs//forecasts//seasonal_naive_forecast.csv')